<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Quality control and filtering – **[fmicompbio/footprintR]{.githubpkg}** book</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./visualize-regions.html" rel="next">
<link href="./reading-data.html" rel="prev">
<link href="./images/footprintR_logo.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./qc-filtering.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Quality control and filtering</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"><strong></strong></a><strong><a href="https://github.com/fmicompbio/footprintR"><em>footprintR</em></a></strong> book 
        <div class="sidebar-tools-main">
    <a href="https://github.com/fmicompbio/footprintR_book/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reading-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Reading data from files</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./qc-filtering.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Quality control and filtering</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./visualize-regions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Visualizing regions with <code>plotRegion</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./nucleosomes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Nucleosome analyses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./scanning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Scanning the genome for regions of interest</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./grouping-reads.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Grouping reads</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple-modalities.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Combining and comparing multiple data modalities</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#creating-a-qc-report" id="toc-creating-a-qc-report" class="nav-link active" data-scroll-target="#creating-a-qc-report"><span class="header-section-number">3.1</span> Creating a QC report</a></li>
  <li><a href="#position-filtering" id="toc-position-filtering" class="nav-link" data-scroll-target="#position-filtering"><span class="header-section-number">3.2</span> Position filtering</a></li>
  <li><a href="#read-filtering" id="toc-read-filtering" class="nav-link" data-scroll-target="#read-filtering"><span class="header-section-number">3.3</span> Read filtering</a>
  <ul class="collapse">
  <li><a href="#filtering-a-summarizedexperiment-object" id="toc-filtering-a-summarizedexperiment-object" class="nav-link" data-scroll-target="#filtering-a-summarizedexperiment-object"><span class="header-section-number">3.3.1</span> Filtering a <code>SummarizedExperiment</code> object</a></li>
  <li><a href="#filtering-a-modbam-file" id="toc-filtering-a-modbam-file" class="nav-link" data-scroll-target="#filtering-a-modbam-file"><span class="header-section-number">3.3.2</span> Filtering a <code>modBam</code> file</a></li>
  </ul></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info"><span class="header-section-number">3.4</span> Session info</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/fmicompbio/footprintR_book/edit/main/qc-filtering.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/fmicompbio/footprintR_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-qc-filtering" class="quarto-section-identifier"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Quality control and filtering</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This chapter explains how to use <a href="https://github.com/fmicompbio/footprintR"><em>footprintR</em></a> to filter single molecule footprinting data. The package contains functionality to calculate a collection of quality statistics for each read, and use these to filter out low-quality reads. This filtering can be done either on the imported <code>SummarizedExperiment</code> object, or directly on the <code>modBam</code> file (which would generate another, filtered <code>modBam</code> file). <a href="https://github.com/fmicompbio/footprintR"><em>footprintR</em></a> also provides several ways to filter out individual genomic positions based on, e.g.&nbsp;the genomic sequence or the read coverage.</p>
<p>We start by loading the required packages. In addition to the software package, we load a <code>BSgenome</code> object providing the mouse genome sequence.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>BSgenomeName <span class="ot">&lt;-</span> <span class="st">"BSgenome.Mmusculus.GENCODE.GRCm39.gencodeM34"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(footprintR)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(BSgenomeName, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(SummarizedExperiment)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(SparseArray)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Load genome</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>gnm <span class="ot">&lt;-</span> <span class="fu">get</span>(BSgenomeName)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">genome</span>(gnm) <span class="ot">&lt;-</span> <span class="st">"mm39"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="creating-a-qc-report" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="creating-a-qc-report"><span class="header-section-number">3.1</span> Creating a QC report</h2>
</section>
<section id="position-filtering" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="position-filtering"><span class="header-section-number">3.2</span> Position filtering</h2>
<p>To illustrate the position-level filtering of imported data, we first read 6mA data from a small genomic region for two samples. We add the sequence context (a single nucleotide) to be able to use this information as a basis for filtering.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">readModBam</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">bamfiles =</span> <span class="fu">c</span>(<span class="at">wt1 =</span> <span class="st">"data/mESC_wt_6mA_rep1.bam"</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">wt2 =</span> <span class="st">"data/mESC_wt_6mA_rep2.bam"</span>),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">modbase =</span> <span class="st">"a"</span>, </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">regions =</span> <span class="st">"chr8:39286301-39287100"</span>, </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">seqinfo =</span> <span class="fu">seqinfo</span>(gnm), </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sequenceContextWidth =</span> <span class="dv">1</span>, </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sequenceReference =</span> gnm</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class: RangedSummarizedExperiment 
dim: 21456 2 
metadata(3): readLevelData variantPositions filteredOutReads
assays(1): mod_prob
rownames(21456): chr8:39269571:- chr8:39269579:- ... chr8:39303298:- chr8:39303300:-
rowData names(1): sequenceContext
colnames(2): wt1 wt2
colData names(4): sample modbase n_reads readInfo</code></pre>
</div>
</div>
<p>The sequence information is stored in the <code>rowData</code> of <code>se</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rowData</span>(se)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>DataFrame with 21456 rows and 1 column
                sequenceContext
                 &lt;DNAStringSet&gt;
chr8:39269571:-               A
chr8:39269579:-               A
chr8:39269588:-               A
chr8:39269589:-               A
chr8:39269612:-               A
...                         ...
chr8:39303283:-               A
chr8:39303284:-               A
chr8:39303297:-               A
chr8:39303298:-               C
chr8:39303300:-               A</code></pre>
</div>
</div>
<p>Position filtering can now be performed with the <a href="https://fmicompbio.github.io/footprintR/reference/filterPositions.html"><code>filterPositions</code></a> function. The <code>filters</code> argument define which filters to apply, as well as the order (sequence context, coverage, removal of positions without non-NA values). Here, we retain only positions where the genome sequence is an A, and the coverage (the number of overlapping reads) is at least five. The <code>assayNameCov</code> argument indicates which assay will be used to define the coverage. If this is a read-level assay (like here), coverage will first be calculated using <a href="https://fmicompbio.github.io/footprintR/reference/flattenReadLevelAssay.html"><code>flattenReadLevelAssay</code></a>. For more precise control, the summary assay can also be manually calculated and added to <code>se</code> beforehand, and specified in <code>assayNameCov</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sefilt <span class="ot">&lt;-</span> <span class="fu">filterPositions</span>(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    se, </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">filters =</span> <span class="fu">c</span>(<span class="st">"sequenceContext"</span>, <span class="st">"coverage"</span>, <span class="st">"all.na"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sequenceContext =</span> <span class="st">"A"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">assayNameCov =</span> <span class="st">"mod_prob"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">minCov =</span> <span class="dv">5</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>sefilt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>class: RangedSummarizedExperiment 
dim: 10957 2 
metadata(3): readLevelData variantPositions filteredOutReads
assays(1): mod_prob
rownames(10957): chr8:39279307:- chr8:39279308:- ... chr8:39298917:- chr8:39298921:-
rowData names(1): sequenceContext
colnames(2): wt1 wt2
colData names(4): sample modbase n_reads readInfo</code></pre>
</div>
</div>
<p>In this case, the position filtering reduced the number of unique positions from 21456 to 10957 by 48.9%. However, the number of non-NA values in the matrix is only reduced from 165914 to 148815 (10.3%), confirming that the filtered-out positions are generally covered only by few reads.</p>
<p>In addition to explicit filtering like here, many other functions in <a href="https://github.com/fmicompbio/footprintR"><em>footprintR</em></a> allow built-in filtering for a specific sequence context.</p>
</section>
<section id="read-filtering" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="read-filtering"><span class="header-section-number">3.3</span> Read filtering</h2>
<section id="filtering-a-summarizedexperiment-object" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="filtering-a-summarizedexperiment-object"><span class="header-section-number">3.3.1</span> Filtering a <code>SummarizedExperiment</code> object</h3>
<p>In addition to the position filtering illustrated above, <a href="https://github.com/fmicompbio/footprintR"><em>footprintR</em></a> also provides functionality for calculating read-level quality scores and filtering out reads with low quality. The calculation of the quality scores is done using the <a href="https://fmicompbio.github.io/footprintR/reference/addReadStats.html"><code>addReadStats</code></a> function, and the filtering is performed via the <a href="https://fmicompbio.github.io/footprintR/reference/filterReads.html"><code>filterReads</code></a> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate read statistics</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>sefilt <span class="ot">&lt;-</span> <span class="fu">addReadStats</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    sefilt, </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">"QC"</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># The calculated read statistics are stored in the colData</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">colData</span>(sefilt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>DataFrame with 2 rows and 5 columns
         sample     modbase   n_reads                                                                    readInfo
    &lt;character&gt; &lt;character&gt; &lt;integer&gt;                                                                      &lt;List&gt;
wt1         wt1           a        34   20.3297:17986:17872:...,19.7905:10469:10421:...,13.2784:7876:7761:...,...
wt2         wt2           a        41 14.1235:22453:22149:...,15.9814:15617:15460:...,14.3505:12359:12212:...,...
                                                                                                        QC
                                                                                                    &lt;List&gt;
wt1 0.0618421:0.0455829:0.967676:...,0.0545563:0.0386562:0.971495:...,0.1317097:0.1049275:0.931608:...,...
wt2       0.195971:0.186199:0.931852:...,0.169650:0.156304:0.944134:...,0.189312:0.176095:0.940588:...,...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>sefilt<span class="sc">$</span>QC<span class="sc">$</span>wt1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>DataFrame with 34 rows and 11 columns
                                         MeanModProb   FracMod  MeanConf MeanConfUnm MeanConfMod FracLowConf IQRModProb
                                           &lt;numeric&gt; &lt;numeric&gt; &lt;numeric&gt;   &lt;numeric&gt;   &lt;numeric&gt;   &lt;numeric&gt;  &lt;numeric&gt;
wt1-d914fb79-7d7a-4a67-bb98-5d1168b057b6   0.0618421 0.0455829  0.967676    0.974548    0.823787   0.0367084  0.0000000
wt1-91aeb981-e093-449d-a6c1-63ad824c8d47   0.0545563 0.0386562  0.971495    0.976905    0.836961   0.0299126  0.0000000
wt1-e3b1cc8a-cde6-4745-9f49-310e68242897   0.1317097 0.1049275  0.931608    0.946834    0.801720   0.0765217  0.1113281
wt1-c5dbb0ee-edfa-4f52-b48b-ac34f7251364   0.1315284 0.1202325  0.953554    0.967183    0.853822   0.0584817  0.0683594
wt1-e11adb8a-0c3d-45cf-9633-d67780a4185f   0.1023139 0.0596330  0.923058    0.936395    0.712730   0.0880734  0.1152344
...                                              ...       ...       ...         ...         ...         ...        ...
wt1-b47f7f9e-623a-4f68-ac0c-905b212f39d7   0.0596196 0.0461133  0.970019    0.977205    0.821373   0.0342556  0.0000000
wt1-7f8eda94-bebd-4ccb-af87-c3e7d65be619   0.0958030 0.0778281  0.954483    0.965575    0.823061   0.0565611  0.0488281
wt1-27f1bc2e-7b63-49b2-a773-0163334f7641   0.1107278 0.0993151  0.966969    0.975328    0.891164   0.0376712  0.0000000
wt1-c32080be-75b0-4923-87dd-41a7cb69d379   0.0394939 0.0268914  0.978357    0.982404    0.831901   0.0190032  0.0000000
wt1-6a7643fc-b95e-49ec-baa8-86fe294e473b   0.1471507 0.1341176  0.960524    0.969679    0.901419   0.0376471  0.0761719
                                         sdModProb Lag1DModProb                               ACModProb
                                         &lt;numeric&gt;    &lt;numeric&gt;                                  &lt;list&gt;
wt1-d914fb79-7d7a-4a67-bb98-5d1168b057b6  0.185359    0.0573043       0.0749726,0.0161444,0.0133524,...
wt1-91aeb981-e093-449d-a6c1-63ad824c8d47  0.173306    0.0598527  0.02945337,-0.00588547,-0.01550006,...
wt1-e3b1cc8a-cde6-4745-9f49-310e68242897  0.254609    0.1531323     0.0319851,-0.0100365, 0.0148677,...
wt1-c5dbb0ee-edfa-4f52-b48b-ac34f7251364  0.284379    0.1417151  0.02581876, 0.03198559,-0.00294165,...
wt1-e11adb8a-0c3d-45cf-9633-d67780a4185f  0.188172    0.1021719       0.0068839,0.0300003,0.0344642,...
...                                            ...          ...                                     ...
wt1-b47f7f9e-623a-4f68-ac0c-905b212f39d7  0.184892    0.0676626  0.01516679, 0.00209322,-0.00613638,...
wt1-7f8eda94-bebd-4ccb-af87-c3e7d65be619  0.232541    0.1095518       0.0832970,0.0437754,0.0433326,...
wt1-27f1bc2e-7b63-49b2-a773-0163334f7641  0.272549    0.1233933    -0.0505126,-0.0494200,-0.0163033,...
wt1-c32080be-75b0-4923-87dd-41a7cb69d379  0.146425    0.0401722 -0.00921144, 0.01132777, 0.00043232,...
wt1-6a7643fc-b95e-49ec-baa8-86fe294e473b  0.310255    0.1415094    -0.0303490,-0.0681595,-0.0348878,...
                                                                         PACModProb
                                                                             &lt;list&gt;
wt1-d914fb79-7d7a-4a67-bb98-5d1168b057b6    -0.05628108,-0.00550086, 0.00561907,...
wt1-91aeb981-e093-449d-a6c1-63ad824c8d47       -0.0248721,-0.0272212,-0.0196893,...
wt1-e3b1cc8a-cde6-4745-9f49-310e68242897       -0.0318656, 0.0126163, 0.0145030,...
wt1-c5dbb0ee-edfa-4f52-b48b-ac34f7251364  0.000585163,-0.035027495,-0.036536268,...
wt1-e11adb8a-0c3d-45cf-9633-d67780a4185f          0.0257367,0.0221382,0.0161219,...
...                                                                             ...
wt1-b47f7f9e-623a-4f68-ac0c-905b212f39d7       -0.0148931,-0.0104126,-0.0223420,...
wt1-7f8eda94-bebd-4ccb-af87-c3e7d65be619 -0.023189216, 0.000722367,-0.018193456,...
wt1-27f1bc2e-7b63-49b2-a773-0163334f7641       -0.0239780, 0.0296459,-0.0448544,...
wt1-c32080be-75b0-4923-87dd-41a7cb69d379        0.0176851,-0.0107225, 0.0719348,...
wt1-6a7643fc-b95e-49ec-baa8-86fe294e473b       -0.0609389, 0.0117622,-0.0752276,...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># In addition, we can filter based on the read info columns added by readModBam</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>sefilt<span class="sc">$</span>readInfo<span class="sc">$</span>wt1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>DataFrame with 34 rows and 5 columns
                                            qscore read_length aligned_length variant_label aligned_fraction
                                         &lt;numeric&gt;   &lt;integer&gt;      &lt;integer&gt;   &lt;character&gt;        &lt;numeric&gt;
wt1-d914fb79-7d7a-4a67-bb98-5d1168b057b6   20.3297       17986          17872            NA         0.993662
wt1-91aeb981-e093-449d-a6c1-63ad824c8d47   19.7905       10469          10421            NA         0.995415
wt1-e3b1cc8a-cde6-4745-9f49-310e68242897   13.2784        7876           7761            NA         0.985399
wt1-c5dbb0ee-edfa-4f52-b48b-ac34f7251364   16.2577        9694           9585            NA         0.988756
wt1-e11adb8a-0c3d-45cf-9633-d67780a4185f   11.2134       14639          14236            NA         0.972471
...                                            ...         ...            ...           ...              ...
wt1-b47f7f9e-623a-4f68-ac0c-905b212f39d7   17.4973       11977           5871            NA         0.490190
wt1-7f8eda94-bebd-4ccb-af87-c3e7d65be619   15.7355        9155           5711            NA         0.623812
wt1-27f1bc2e-7b63-49b2-a773-0163334f7641   18.1292        9097           6047            NA         0.664725
wt1-c32080be-75b0-4923-87dd-41a7cb69d379   22.4457        7597           7577            NA         0.997367
wt1-6a7643fc-b95e-49ec-baa8-86fe294e473b   16.8056        4182           2419            NA         0.578431</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the read statistics to set appropriate filter thresholds</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotReadStats</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    sefilt</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="qc-filtering_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform filtering</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>sefilt <span class="ot">&lt;-</span> <span class="fu">filterReads</span>(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    sefilt,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">minQscore =</span> <span class="dv">13</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">maxFracLowConf =</span> <span class="fl">0.1</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">minAlignedLength =</span> <span class="dv">5000</span>, </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">removeAllNApos =</span> <span class="cn">TRUE</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Filtering statistics are stored in the <code>metadata</code> of the filtered <code>SummarizedExperiment</code> object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">metadata</span>(sefilt)<span class="sc">$</span>filteredOutReads</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$wt1
&lt;9 x 7 SparseMatrix&gt; of type "logical" [nzcount=10 (16%)]:
                                                  Qscore         Entropy     FracLowConf ... AlignedFraction
wt1-e11adb8a-0c3d-45cf-9633-d67780a4185f            TRUE           FALSE           FALSE   .           FALSE
wt1-1c916f3a-030c-4c18-9f76-408840e6a3fa            TRUE           FALSE           FALSE   .           FALSE
wt1-2f9885e3-91d5-4753-961d-439d64fbd301            TRUE           FALSE           FALSE   .           FALSE
wt1-840df614-693f-40f5-9b35-7495eac426f1           FALSE           FALSE           FALSE   .           FALSE
wt1-51e19b4b-6baa-4982-88f3-a16a9fad78c6           FALSE           FALSE           FALSE   .           FALSE
wt1-419d45a8-6e9e-41cc-ae32-9105049b8cd7            TRUE           FALSE           FALSE   .           FALSE
wt1-c1eef755-3d3f-4f33-b87a-d896ec1a26cc           FALSE           FALSE           FALSE   .           FALSE
wt1-d87a7efd-367f-42f6-b9af-e112610e945b            TRUE           FALSE           FALSE   .           FALSE
wt1-6a7643fc-b95e-49ec-baa8-86fe294e473b           FALSE           FALSE           FALSE   .           FALSE
                                                   AllNA
wt1-e11adb8a-0c3d-45cf-9633-d67780a4185f           FALSE
wt1-1c916f3a-030c-4c18-9f76-408840e6a3fa           FALSE
wt1-2f9885e3-91d5-4753-961d-439d64fbd301           FALSE
wt1-840df614-693f-40f5-9b35-7495eac426f1           FALSE
wt1-51e19b4b-6baa-4982-88f3-a16a9fad78c6           FALSE
wt1-419d45a8-6e9e-41cc-ae32-9105049b8cd7           FALSE
wt1-c1eef755-3d3f-4f33-b87a-d896ec1a26cc           FALSE
wt1-d87a7efd-367f-42f6-b9af-e112610e945b           FALSE
wt1-6a7643fc-b95e-49ec-baa8-86fe294e473b           FALSE

$wt2
&lt;12 x 7 SparseMatrix&gt; of type "logical" [nzcount=16 (19%)]:
                                                  Qscore         Entropy     FracLowConf ... AlignedFraction
wt2-b58992e1-d311-49d7-bf22-81fd390687b5            TRUE           FALSE           FALSE   .           FALSE
wt2-e145db43-4658-4dcc-8f58-78fb09544770            TRUE           FALSE            TRUE   .           FALSE
wt2-eac97b86-e3fc-4d19-8a02-08bd861077b5            TRUE           FALSE           FALSE   .           FALSE
wt2-e06432c5-189d-4c1c-8a5b-025c2d68fee5            TRUE           FALSE            TRUE   .           FALSE
wt2-5a2f30be-48c9-4b0a-8ab1-83d54c71ef56           FALSE           FALSE           FALSE   .           FALSE
                                     ...               .               .               .   .               .
wt2-fac12814-a86d-4d07-9596-d9ea4943580e           FALSE           FALSE           FALSE   .           FALSE
wt2-f77f5ae9-dd3a-4e08-a390-7e80868433a7            TRUE           FALSE            TRUE   .           FALSE
wt2-fda332ae-02de-4391-9cff-620c1ae8799f           FALSE           FALSE           FALSE   .           FALSE
wt2-b6efe1fe-f2b9-4f69-bb61-f4a741969a52           FALSE           FALSE            TRUE   .           FALSE
wt2-d0b3f6f8-c5d3-477e-b4c4-02dcd4602767           FALSE           FALSE           FALSE   .           FALSE
                                                   AllNA
wt2-b58992e1-d311-49d7-bf22-81fd390687b5           FALSE
wt2-e145db43-4658-4dcc-8f58-78fb09544770           FALSE
wt2-eac97b86-e3fc-4d19-8a02-08bd861077b5           FALSE
wt2-e06432c5-189d-4c1c-8a5b-025c2d68fee5           FALSE
wt2-5a2f30be-48c9-4b0a-8ab1-83d54c71ef56           FALSE
                                     ...               .
wt2-fac12814-a86d-4d07-9596-d9ea4943580e           FALSE
wt2-f77f5ae9-dd3a-4e08-a390-7e80868433a7           FALSE
wt2-fda332ae-02de-4391-9cff-620c1ae8799f           FALSE
wt2-b6efe1fe-f2b9-4f69-bb61-f4a741969a52           FALSE
wt2-d0b3f6f8-c5d3-477e-b4c4-02dcd4602767           FALSE</code></pre>
</div>
</div>
</section>
<section id="filtering-a-modbam-file" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="filtering-a-modbam-file"><span class="header-section-number">3.3.2</span> Filtering a <code>modBam</code> file</h3>
</section>
</section>
<section id="session-info" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="session-info"><span class="header-section-number">3.4</span> Session info</h2>
<details>
<summary>
<b> Click to view session info </b>
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>sessioninfo<span class="sc">::</span><span class="fu">session_info</span>(<span class="at">info =</span> <span class="st">"packages"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>═ Session info ═══════════════════════════════════════════════════════════════════════════════════════════════════════
─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────
 package                                      * version    date (UTC) lib source
 abind                                        * 1.4-8      2024-09-12 [1] CRAN (R 4.4.2)
 Biobase                                      * 2.66.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 BiocGenerics                                 * 0.52.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 BiocIO                                       * 1.16.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 BiocParallel                                 * 1.40.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 Biostrings                                   * 2.74.1     2024-12-16 [1] Bioconductor 3.20 (R 4.4.2)
 bitops                                         1.0-9      2024-10-03 [1] CRAN (R 4.4.2)
 BSgenome                                     * 1.74.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 BSgenome.Mmusculus.GENCODE.GRCm39.gencodeM34 * 0.1.0      2024-11-01 [1] Bioconductor
 cli                                            3.6.4      2025-02-13 [1] CRAN (R 4.4.2)
 codetools                                      0.2-20     2024-03-31 [2] CRAN (R 4.4.2)
 crayon                                         1.5.3      2024-06-20 [1] CRAN (R 4.4.2)
 curl                                           6.2.2      2025-03-24 [1] CRAN (R 4.4.2)
 data.table                                     1.17.0     2025-02-22 [1] CRAN (R 4.4.2)
 DelayedArray                                   0.32.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 dichromat                                      2.0-0.1    2022-05-02 [1] CRAN (R 4.4.2)
 digest                                         0.6.37     2024-08-19 [1] CRAN (R 4.4.2)
 dplyr                                          1.1.4      2023-11-17 [1] CRAN (R 4.4.2)
 evaluate                                       1.0.3      2025-01-10 [1] CRAN (R 4.4.2)
 farver                                         2.1.2      2024-05-13 [1] CRAN (R 4.4.2)
 fastmap                                        1.2.0      2024-05-15 [1] CRAN (R 4.4.2)
 footprintR                                   * 0.3.2      2025-03-26 [1] Github (fmicompbio/footprintR@04d9c8f)
 generics                                       0.1.3      2022-07-05 [1] CRAN (R 4.4.2)
 GenomeInfoDb                                 * 1.42.3     2025-01-27 [1] Bioconductor 3.20 (R 4.4.2)
 GenomeInfoDbData                               1.2.13     2024-10-31 [1] Bioconductor
 GenomicAlignments                              1.42.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 GenomicRanges                                * 1.58.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 ggforce                                        0.4.2      2024-02-19 [1] CRAN (R 4.4.2)
 ggplot2                                        3.5.1      2024-04-23 [1] CRAN (R 4.4.2)
 glue                                           1.8.0      2024-09-30 [1] CRAN (R 4.4.2)
 gtable                                         0.3.6      2024-10-25 [1] CRAN (R 4.4.2)
 htmltools                                      0.5.8.1    2024-04-04 [1] CRAN (R 4.4.2)
 htmlwidgets                                    1.6.4      2023-12-06 [1] CRAN (R 4.4.2)
 httr                                           1.4.7      2023-08-15 [1] CRAN (R 4.4.2)
 IRanges                                      * 2.40.1     2024-12-05 [1] Bioconductor 3.20 (R 4.4.2)
 jsonlite                                       1.9.1      2025-03-03 [1] CRAN (R 4.4.2)
 knitr                                          1.50       2025-03-16 [1] CRAN (R 4.4.2)
 labeling                                       0.4.3      2023-08-29 [1] CRAN (R 4.4.2)
 lattice                                        0.22-6     2024-03-20 [2] CRAN (R 4.4.2)
 lifecycle                                      1.0.4      2023-11-07 [1] CRAN (R 4.4.2)
 magrittr                                       2.0.3      2022-03-30 [1] CRAN (R 4.4.2)
 MASS                                           7.3-61     2024-06-13 [2] CRAN (R 4.4.2)
 Matrix                                       * 1.7-1      2024-10-18 [2] CRAN (R 4.4.2)
 MatrixGenerics                               * 1.18.1     2025-01-09 [1] Bioconductor 3.20 (R 4.4.2)
 matrixStats                                  * 1.5.0      2025-01-07 [1] CRAN (R 4.4.2)
 patchwork                                      1.3.0      2024-09-16 [1] CRAN (R 4.4.2)
 pillar                                         1.10.1     2025-01-07 [1] CRAN (R 4.4.2)
 pkgconfig                                      2.0.3      2019-09-22 [1] CRAN (R 4.4.2)
 polyclip                                       1.10-7     2024-07-23 [1] CRAN (R 4.4.2)
 purrr                                          1.0.4      2025-02-05 [1] CRAN (R 4.4.2)
 R6                                             2.6.1      2025-02-15 [1] CRAN (R 4.4.2)
 RColorBrewer                                   1.1-3      2022-04-03 [1] CRAN (R 4.4.2)
 Rcpp                                           1.0.14     2025-01-12 [1] CRAN (R 4.4.2)
 RCurl                                          1.98-1.17  2025-03-22 [1] CRAN (R 4.4.2)
 restfulr                                       0.0.15     2022-06-16 [1] CRAN (R 4.4.2)
 rjson                                          0.2.23     2024-09-16 [1] CRAN (R 4.4.2)
 rlang                                          1.1.5      2025-01-17 [1] CRAN (R 4.4.2)
 rmarkdown                                      2.29       2024-11-04 [1] CRAN (R 4.4.2)
 Rsamtools                                      2.22.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 rstudioapi                                     0.17.1     2024-10-22 [1] CRAN (R 4.4.2)
 rtracklayer                                  * 1.66.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 S4Arrays                                     * 1.6.0      2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 S4Vectors                                    * 0.44.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 scales                                         1.3.0.9000 2025-01-29 [1] Github (r-lib/scales@ee03582)
 sessioninfo                                    1.2.3      2025-02-05 [1] CRAN (R 4.4.2)
 SparseArray                                  * 1.6.2      2025-02-20 [1] Bioconductor 3.20 (R 4.4.2)
 SummarizedExperiment                         * 1.36.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 tibble                                         3.2.1      2023-03-20 [1] CRAN (R 4.4.2)
 tidyr                                          1.3.1      2024-01-24 [1] CRAN (R 4.4.2)
 tidyselect                                     1.2.1      2024-03-11 [1] CRAN (R 4.4.2)
 tweenr                                         2.0.3      2024-02-26 [1] CRAN (R 4.4.2)
 UCSC.utils                                     1.2.0      2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 vctrs                                          0.6.5      2023-12-01 [1] CRAN (R 4.4.2)
 withr                                          3.0.2      2024-10-28 [1] CRAN (R 4.4.2)
 xfun                                           0.51       2025-02-19 [1] CRAN (R 4.4.2)
 XML                                            3.99-0.18  2025-01-01 [1] CRAN (R 4.4.2)
 XVector                                      * 0.46.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 yaml                                           2.3.10     2024-07-26 [1] CRAN (R 4.4.2)
 zlibbioc                                       1.52.0     2024-10-29 [1] Bioconductor 3.20 (R 4.4.2)
 zoo                                            1.8-13     2025-02-22 [1] CRAN (R 4.4.2)

 [1] /tungstenfs/groups/gbioinfo/Appz/R/BioC/R-4.4-release-foss-2024.05_BioC-3.20-release-foss-2024.05
 [2] /tungstenfs/groups/gbioinfo/Appz/easybuild/software/R/4.4.2-foss-2024.05/lib64/R/library
 * ── Packages attached to the search path.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</code></pre>
</div>
</div>
</details>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/fmicompbio\.github\.io\/footprintR_book");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./reading-data.html" class="pagination-link" aria-label="Reading data from files">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Reading data from files</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./visualize-regions.html" class="pagination-link" aria-label="Visualizing regions with `plotRegion`">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Visualizing regions with <code>plotRegion</code></span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/fmicompbio/footprintR_book/edit/main/qc-filtering.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/fmicompbio/footprintR_book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>